import { Fragment, useContext, useRef, useState, type JSX } from "react";

import DataContext from "@/context/Data.context";
import DatabaseSchema from "@/data/schema.json";

import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs";

const TableSummary = (): JSX.Element => {
	const data = useContext(DataContext);
	const schemas = useRef(Object.keys(DatabaseSchema.properties) as (keyof typeof DatabaseSchema["properties"])[]);
	const [schema, setSchema] = useState<keyof typeof DatabaseSchema["properties"]>(schemas.current[0]);

	const defaultHeaders = ["auto_generated", "not_set", "foreign_key"];
	const autoGenerated = ["id", "created_at", "updated_at"];

	const renderTabs = (): JSX.Element[] => {
		const tables = DatabaseSchema.properties[schema].properties.Tables;
		const tablesNames = Object.keys(tables.properties);

		return tablesNames.map((val) => (
			<TabsTrigger
				key={val}
				value={val}
			>
				{val}
			</TabsTrigger>
		));
	};

	const renderSelects = (val: string, foreignKeys: string[]): JSX.Element => {
		const defaultVal = autoGenerated.includes(val) ? "auto_generated" : foreignKeys.includes(val) ? "foreign_key" : "not_set";

		return (
			<Select
				defaultValue={defaultVal}
				onValueChange={(newVal) => {
					const headerIndex = data.mapping.findIndex((el) => el[0] === val);

					if (headerIndex === -1) {
						data.setMapping([
							...data.mapping,
							[val, newVal],
						]);
					} else {
						const newMapping = [...data.mapping];
						newMapping[headerIndex] = [val, newVal];

						data.setMapping(newMapping);
					}
				}}
			>
				<SelectTrigger>
					<SelectValue placeholder={defaultVal} />
				</SelectTrigger>

				{renderSelectItems()}
			</Select>
		);
	};

	const renderSelectItems = (): JSX.Element => {
		return (
			<SelectContent>
				{[...defaultHeaders, ...data.headers].flatMap((val) => {
					if (!val?.length) {
						return [];
					}

					return (
						<SelectItem
							value={val}
							key={val}
						>
							{val}
						</SelectItem>
					);
				})}
			</SelectContent>
		);
	};

	const renderContentlessBody = (val: string): JSX.Element => {
		if (!data.headers?.length) {
			return (
				<Fragment />
			);
		}

		// To Do: If mapping saved, return fragment

		const tables = (DatabaseSchema.properties[schema]).properties.Tables;
		let foreignKeys: string[] = [];

		try {
			const typedItems = (tables.properties[val as keyof typeof tables.properties].properties.Relationships as any).items as {
				properties: { columns: { items: { const: string }[] };
			}; }[];

			foreignKeys = typedItems?.map((item) => item.properties.columns.items[0].const) || [];
		} catch {
			console.log("No foreign keys");
		}

		return (
			<TableBody>
				<TableRow>
					{Object.keys(tables.properties[val as keyof typeof tables.properties].properties.Row.properties).map((header) => (
						<TableCell key={header}>{renderSelects(header, foreignKeys)}</TableCell>
					))}
				</TableRow>
			</TableBody>
		);
	};

	const renderContentBody = (): JSX.Element => {
		// To Do: If no mapping saved, return fragment

		// Return data

		return <Fragment />;
	};

	const renderTabsContent = (): JSX.Element[] => {
		const tables = (DatabaseSchema.properties[schema]).properties.Tables;
		const tablesNames = Object.keys(tables.properties);

		return tablesNames.map((val) => (
			<TabsContent
				key={val}
				value={val}
			>
				<Table>
					<TableHeader>
						<TableRow>
							{Object.keys(tables.properties[val as keyof typeof tables.properties].properties.Row.properties).map((header) => (
								<TableHead key={header}>{header}</TableHead>
							))}
						</TableRow>
					</TableHeader>

					{renderContentlessBody(val)}

					{renderContentBody()}
				</Table>
			</TabsContent>
		));
	};

	const renderSchemaNames = (): JSX.Element[] => {
		return schemas.current.map((schemaName) => (
			<TabsTrigger
				key={schemaName}
				value={schemaName}
			>
				{schemaName}
			</TabsTrigger>
		));
	};

	const renderContent = (): JSX.Element[] => {
		return schemas.current.map((schemaName) => {
			return (
				<TabsContent
					key={schemaName}
					value={schemaName}
				>
					<Tabs
						defaultValue={Object.keys(DatabaseSchema.properties[schemaName].properties.Tables.properties)[0]}
						onValueChange={() => {
							data.setMapping([]);
						}}
					>
						<TabsList>
							{renderTabs()}
						</TabsList>

						{renderTabsContent()}
					</Tabs>
				</TabsContent>
			);
		});
	};

	return (
		<Tabs
			defaultValue={schemas.current[0]}
			className={"w-[1440px]"}
			onValueChange={(val) => {
				setSchema(val as keyof typeof DatabaseSchema["properties"]);
			}}
		>
			<TabsList>
				{renderSchemaNames()}
			</TabsList>

			{renderContent()}
		</Tabs>
	);
};

export default TableSummary;
